name: Add Songs to Playlist - Spotify
on:
  repository_dispatch:
    types: [appsheet_trigger]

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install spotipy google-cloud-storage gspread

      - name: Run update script
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        run: python add_to_playlist_spotify.py
