name: Apple Music Scraper

on:
  # Run at 9AM UTC daily
  schedule:
    - cron: '0 5 * * *'
  
  # Manual trigger option
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-cloud-storage requests beautifulsoup4 ytmusicapi
      
      - name: Create OAuth file from secret
        run: echo '${{ secrets.YOUTUBE_OAUTH_JSON }}' > oauth.json
      
      - name: Run scraper
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
        run: python apple_music.py
