name: Video Posting Pipeline

on:
  repository_dispatch:
    types: [appsheet_trigger]

jobs:
  update-spotify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt
      - run: python add_to_playlist_spotify.py
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          PYTHONUNBUFFERED: 1

  update-youtube-music:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt
      - run: python add_to_playlist_youtube.py
        env:
          YOUTUBE_CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID }}
          YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
          YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
          YOUTUBE_PLAYLIST_ID: ${{ secrets.YOUTUBE_PLAYLIST_ID }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          PYTHONUNBUFFERED: 1

  stitch-videos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt
      - run: python video_stitcher.py
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          PYTHONUNBUFFERED: 1

  post-instagram:
    runs-on: ubuntu-latest
    needs: stitch-videos
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt
      - run: python poster_instagram.py
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
          INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}
          INSTAGRAM_ACCOUNT_ID: ${{ secrets.INSTAGRAM_ACCOUNT_ID }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          PYTHONUNBUFFERED: 1

  post-youtube:
    runs-on: ubuntu-latest
    needs: stitch-videos
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt
      - run: python poster_youtube.py
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
          YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
          YOUTUBE_CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID }}
          YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
          PYTHONUNBUFFERED: 1

  post-threads:
    runs-on: ubuntu-latest
    needs: stitch-videos
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt
      - run: python poster_threads.py
        env:
          THREADS_ACCESS_TOKEN: ${{ secrets.THREADS_ACCESS_TOKEN }}
          THREADS_USER_ID: ${{ secrets.THREADS_USER_ID }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
          PYTHONUNBUFFERED: 1

  post-bluesky:
    runs-on: ubuntu-latest
    needs: stitch-videos
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt
      - run: python poster_bluesky.py
        env:
          BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
          BLUESKY_APP_PASSWORD: ${{ secrets.BLUESKY_APP_PASSWORD }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
          PYTHONUNBUFFERED: 1

  post-facebook:
    runs-on: ubuntu-latest
    needs: stitch-videos
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt
      - run: python poster_facebook.py
        env:
          FACEBOOK_ACCESS_TOKEN: ${{ secrets.FACEBOOK_ACCESS_TOKEN }}
          FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
          PYTHONUNBUFFERED: 1

  post-tiktok:
    runs-on: ubuntu-latest
    needs: stitch-videos
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt
      - run: python poster_tiktok.py
        env:
          UPLOAD_POST_API_KEY: ${{ secrets.UPLOAD_POST_API_KEY }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
          PYTHONUNBUFFERED: 1

  post-pinterest:
    runs-on: ubuntu-latest
    needs: stitch-videos
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt
      - run: python poster_pinterest.py
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
          PYTHONUNBUFFERED: 1
