name: Test Webhook Trigger
on:
  repository_dispatch:
    types: [appsheet_trigger]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print trigger info
        run: |
          echo "Workflow triggered!"
          echo "Source: ${{ github.event.inputs.source }}"
          echo "Timestamp: $(date)"

      - name: Simulate processing
        run: |
          echo "Processing songs..."
          sleep 5
          echo "Done!"
