name: YouTube Shorts Uploader
on:
  workflow_dispatch:

jobs:
  upload-youtube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt
      - run: python poster_youtube.py
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
          YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
          YOUTUBE_CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID }}
          YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
