name: Generate Music Videos

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  create-videos:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg imagemagick
    
    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install decorator proglog requests tqdm numpy
        git clone https://github.com/Zulko/moviepy.git
        cd moviepy
        pip install -e .
        cd ..
        pip install pillow google-cloud-storage
    
    - name: Configure ImageMagick
      run: sudo sed -i 's/none/read,write/g' /etc/ImageMagick-6/policy.xml
    
    - name: Set up GCloud Auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v2
    
    - name: Run video creator
      run: python video_creator.py
    
    - name: Commit and push
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add preview_*.mp4
        git commit -m "Add new music preview videos" || echo "No changes to commit"
        git push
