name: Generate Weekly Rotation Videos

on:
  schedule:
    - cron: '30 7 * * *'  # Run daily at 7:30 UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  generate-videos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run script
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          GCS_BUCKET_NAME: bebop_data
        run: python video_creator.py
