name: Generate Weekly Rotation Videos

on:
  schedule:
    - cron: '30 7 * * *'  # Run daily at 7:30 UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  generate-videos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg imagemagick
          
          # Fix ImageMagick policy to allow text operations
          sudo cp /etc/ImageMagick-6/policy.xml /etc/ImageMagick-6/policy.xml.bak
          sudo sed -i 's/rights="none" pattern="PS"/rights="read|write" pattern="PS"/' /etc/ImageMagick-6/policy.xml
          sudo sed -i 's/rights="none" pattern="EPS"/rights="read|write" pattern="EPS"/' /etc/ImageMagick-6/policy.xml
          sudo sed -i 's/rights="none" pattern="PDF"/rights="read|write" pattern="PDF"/' /etc/ImageMagick-6/policy.xml
          sudo sed -i 's/rights="none" pattern="XPS"/rights="read|write" pattern="XPS"/' /etc/ImageMagick-6/policy.xml
          
          # Alternatively, allow all operations (less secure but works)
          echo '<policymap>' | sudo tee /etc/ImageMagick-6/policy.xml
          echo '  <policy domain="resource" name="memory" value="2GiB"/>' | sudo tee -a /etc/ImageMagick-6/policy.xml
          echo '  <policy domain="resource" name="disk" value="4GiB"/>' | sudo tee -a /etc/ImageMagick-6/policy.xml
          echo '  <policy domain="resource" name="time" value="120"/>' | sudo tee -a /etc/ImageMagick-6/policy.xml
          echo '</policymap>' | sudo tee -a /etc/ImageMagick-6/policy.xml
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run script
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          GCS_BUCKET_NAME: bebop_data
        run: python video_creator.py
